project:
  type: website
  output-dir: docs
website:
  title: "A Journey Within"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: workshops.qmd
        text: Workshops
      - href: blog.qmd
        text: Blog
      - about.qmd
  sidebar:
    style: "docked"
    logo: "./images/Ashlin_image2.jpeg"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/Ashlin-Rose-Manoj
      - icon: twitter
        text: Twitter
        url: https://twitter.com
      - icon: Email
      - text: "Email"
        url: mailto:ashlinrosemanoj@gmail.com
      - icon: linkedin
        text: LinkedIn
        url: https://www.linkedin.com/in/ashlin-rose-manoj/



format:
  html:
    theme: minty
    css: styles.css
    toc: true
  


